# Site settings
title: emfjson
email: g.hillairet@gmail.com
description: "JSON Binding for EMF (Eclipse Modeling Framework)."
baseurl: "/emfjson"
url: "https://ghillairet.github.io/emfjson"
github_username:  ghillairet

# Build settings
markdown: redcarpet
redcarpet:
    extensions: ["with_toc_data"]
permalink: pretty
highlighter: pygments
sass:
    sass_dir: _sass
