# Site settings
title: EMF JSON
email: g.hillairet@gmail.com
description: "JSON Binding for EMF (Eclipse Modeling Framework)."
baseurl: ""
url: "http://www.emfjson.org"
github_username:  ghillairet

# Build settings
markdown: kramdown
permalink: pretty
sass:
    style: :compressed
    sass_dir: _sass
